import type { Clinic, Staff, Menu, Shift, Reservation } from '@/types/clinic'
import { addDays, format, startOfWeek } from 'date-fns'

const NOW = new Date().toISOString()
const TODAY = format(new Date(), 'yyyy-MM-dd')
const WEEK_START = format(startOfWeek(new Date(), { weekStartsOn: 1 }), 'yyyy-MM-dd')

export const DEMO_CLINICS: Clinic[] = [
  {
    id: 'clinic-1',
    name: 'イトー鍼灸整骨院（本院）',
    address: '〒299-0211 千葉県袖ケ浦市野里1770-3',
    phone: '0438-75-5557',
    open_time: '09:00',
    close_time: '19:30',
    is_active: true,
    sort_order: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'clinic-2',
    name: 'ストレッチ鍼灸イトー整骨院',
    address: '〒299-0246 千葉県袖ケ浦市長浦駅前2-4-10',
    phone: '0438-53-8853',
    open_time: '09:30',
    close_time: '20:00',
    is_active: true,
    sort_order: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'clinic-3',
    name: 'SANRI鍼灸整骨院（イオンモール富津店）',
    address: '〒293-0012 千葉県富津市青木1丁目5番地1 イオンモール富津3F',
    phone: '0439-32-1771',
    open_time: '10:00',
    close_time: '20:00',
    is_active: true,
    sort_order: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'clinic-4',
    name: '伊藤リハビリセンター',
    address: '〒299-0211 千葉県袖ケ浦市野里1770-3',
    phone: '0438-75-7737',
    open_time: '09:00',
    close_time: '18:00',
    is_active: true,
    sort_order: 3,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'clinic-5',
    name: 'はり・きゅう HaRi-na',
    address: '〒299-0246 千葉県袖ケ浦市長浦駅前3-3-6',
    phone: '',
    open_time: '09:30',
    close_time: '19:00',
    is_active: true,
    sort_order: 4,
    created_at: NOW,
    updated_at: NOW,
  },
]

export const DEMO_STAFF: Staff[] = [
  // 本院
  {
    id: 'staff-1',
    clinic_id: 'clinic-1',
    name: '田中 誠',
    role: '柔道整復師',
    is_bookable: true,
    is_active: true,
    sort_order: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'staff-2',
    clinic_id: 'clinic-1',
    name: '佐藤 美咲',
    role: '鍼灸師',
    is_bookable: true,
    is_active: true,
    sort_order: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'staff-3',
    clinic_id: 'clinic-1',
    name: '鈴木 健太',
    role: 'あん摩マッサージ指圧師',
    is_bookable: true,
    is_active: true,
    sort_order: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  // ストレッチ院
  {
    id: 'staff-4',
    clinic_id: 'clinic-2',
    name: '伊藤 圭介',
    role: '柔道整復師',
    is_bookable: true,
    is_active: true,
    sort_order: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'staff-5',
    clinic_id: 'clinic-2',
    name: '中村 涼子',
    role: '鍼灸師',
    is_bookable: true,
    is_active: true,
    sort_order: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  // SANRI
  {
    id: 'staff-6',
    clinic_id: 'clinic-3',
    name: '山田 花子',
    role: '鍼灸師',
    is_bookable: true,
    is_active: true,
    sort_order: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'staff-7',
    clinic_id: 'clinic-3',
    name: '渡辺 拓也',
    role: '柔道整復師',
    is_bookable: true,
    is_active: true,
    sort_order: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  // 伊藤リハビリセンター
  {
    id: 'staff-8',
    clinic_id: 'clinic-4',
    name: '小林 梨花',
    role: 'あん摩マッサージ指圧師',
    is_bookable: true,
    is_active: true,
    sort_order: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  // HaRi-na
  {
    id: 'staff-9',
    clinic_id: 'clinic-5',
    name: '高橋 彩',
    role: '鍼灸師',
    is_bookable: true,
    is_active: true,
    sort_order: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'staff-10',
    clinic_id: 'clinic-5',
    name: '斎藤 なな',
    role: '鍼灸師',
    is_bookable: true,
    is_active: true,
    sort_order: 1,
    created_at: NOW,
    updated_at: NOW,
  },
]

export const DEMO_MENUS: Menu[] = [
  // ── 本院（clinic-1）──────────────────────────────
  {
    id: 'menu-1',
    clinic_id: 'clinic-1',
    name: 'ほぐし・マッサージ 30分',
    duration_min: 30,
    price: 3250,
    visit_type: 'both',
    is_active: true,
    sort_order: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'menu-2',
    clinic_id: 'clinic-1',
    name: 'ほぐし・マッサージ 50分',
    duration_min: 50,
    price: 4900,
    visit_type: 'both',
    is_active: true,
    sort_order: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'menu-3',
    clinic_id: 'clinic-1',
    name: 'ほぐし・マッサージ 70分',
    duration_min: 70,
    price: 6700,
    visit_type: 'both',
    is_active: true,
    sort_order: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'menu-4',
    clinic_id: 'clinic-1',
    name: '骨格矯正',
    duration_min: 20,
    price: 2150,
    visit_type: 'both',
    is_active: true,
    sort_order: 3,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'menu-5',
    clinic_id: 'clinic-1',
    name: '鍼灸治療 30分',
    duration_min: 30,
    price: 3250,
    visit_type: 'both',
    is_active: true,
    sort_order: 4,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'menu-6',
    clinic_id: 'clinic-1',
    name: '鍼灸治療 50分',
    duration_min: 50,
    price: 4900,
    visit_type: 'both',
    is_active: true,
    sort_order: 5,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'menu-7',
    clinic_id: 'clinic-1',
    name: '保険治療（外傷）',
    duration_min: 30,
    price: 0,
    visit_type: 'both',
    is_active: true,
    sort_order: 6,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'menu-8',
    clinic_id: 'clinic-1',
    name: '初診カウンセリング',
    duration_min: 90,
    price: 0,
    visit_type: 'first',
    is_active: true,
    sort_order: 7,
    created_at: NOW,
    updated_at: NOW,
  },
  // ── ストレッチ院（clinic-2）──────────────────────────────
  {
    id: 'menu-c2-1',
    clinic_id: 'clinic-2',
    name: 'IMC式矯正治療',
    duration_min: 60,
    price: 5500,
    visit_type: 'both',
    is_active: true,
    sort_order: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'menu-c2-2',
    clinic_id: 'clinic-2',
    name: '楽トレ EMS',
    duration_min: 30,
    price: 3300,
    visit_type: 'both',
    is_active: true,
    sort_order: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'menu-c2-3',
    clinic_id: 'clinic-2',
    name: 'ほぐし・マッサージ 30分',
    duration_min: 30,
    price: 3250,
    visit_type: 'both',
    is_active: true,
    sort_order: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'menu-c2-4',
    clinic_id: 'clinic-2',
    name: '鍼灸治療 30分',
    duration_min: 30,
    price: 3250,
    visit_type: 'both',
    is_active: true,
    sort_order: 3,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'menu-c2-5',
    clinic_id: 'clinic-2',
    name: '骨格矯正',
    duration_min: 20,
    price: 2150,
    visit_type: 'both',
    is_active: true,
    sort_order: 4,
    created_at: NOW,
    updated_at: NOW,
  },
  // ── SANRI（clinic-3）──────────────────────────────
  {
    id: 'menu-c3-1',
    clinic_id: 'clinic-3',
    name: 'ほぐし・マッサージ 30分',
    duration_min: 30,
    price: 3250,
    visit_type: 'both',
    is_active: true,
    sort_order: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'menu-c3-2',
    clinic_id: 'clinic-3',
    name: 'ほぐし・マッサージ 50分',
    duration_min: 50,
    price: 4900,
    visit_type: 'both',
    is_active: true,
    sort_order: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'menu-c3-3',
    clinic_id: 'clinic-3',
    name: '鍼灸治療 30分',
    duration_min: 30,
    price: 3250,
    visit_type: 'both',
    is_active: true,
    sort_order: 2,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'menu-c3-4',
    clinic_id: 'clinic-3',
    name: '美容鍼',
    duration_min: 60,
    price: 5500,
    visit_type: 'both',
    is_active: true,
    sort_order: 3,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'menu-c3-5',
    clinic_id: 'clinic-3',
    name: '酸素カプセル 30分',
    duration_min: 30,
    price: 1650,
    visit_type: 'both',
    is_active: true,
    sort_order: 4,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'menu-c3-6',
    clinic_id: 'clinic-3',
    name: '酸素カプセル 50分',
    duration_min: 50,
    price: 2750,
    visit_type: 'both',
    is_active: true,
    sort_order: 5,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'menu-c3-7',
    clinic_id: 'clinic-3',
    name: '骨格矯正',
    duration_min: 20,
    price: 2150,
    visit_type: 'both',
    is_active: true,
    sort_order: 6,
    created_at: NOW,
    updated_at: NOW,
  },
  // ── 伊藤リハビリセンター（clinic-4）──────────────────────────────
  {
    id: 'menu-c4-0',
    clinic_id: 'clinic-4',
    name: '訪問リハビリマッサージ 60分',
    duration_min: 60,
    price: 0,
    visit_type: 'both',
    is_active: true,
    sort_order: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'menu-c4-0b',
    clinic_id: 'clinic-4',
    name: '訪問リハビリマッサージ 90分',
    duration_min: 90,
    price: 0,
    visit_type: 'both',
    is_active: true,
    sort_order: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  // ── はり・きゅう HaRi-na（clinic-5）──────────────────────────────
  {
    id: 'menu-c5-1',
    clinic_id: 'clinic-5',
    name: '美容鍼',
    duration_min: 60,
    price: 5500,
    visit_type: 'both',
    is_active: true,
    sort_order: 0,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'menu-c5-2',
    clinic_id: 'clinic-5',
    name: '鍼灸治療 30分',
    duration_min: 30,
    price: 3250,
    visit_type: 'both',
    is_active: true,
    sort_order: 1,
    created_at: NOW,
    updated_at: NOW,
  },
  {
    id: 'menu-c5-3',
    clinic_id: 'clinic-5',
    name: '鍼灸治療 60分',
    duration_min: 60,
    price: 5500,
    visit_type: 'both',
    is_active: true,
    sort_order: 2,
    created_at: NOW,
    updated_at: NOW,
  },
]

function makeReservation(
  id: string,
  date: string,
  startHour: number,
  startMin: number,
  durationMin: number,
  staffId: string,
  menuId: string,
  patientName: string,
  status: Reservation['status'] = 'confirmed',
  phone?: string,
  memo?: string,
): Reservation {
  const start = new Date(`${date}T${String(startHour).padStart(2, '0')}:${String(startMin).padStart(2, '0')}:00`)
  const end = new Date(start.getTime() + durationMin * 60 * 1000)
  return {
    id,
    clinic_id: 'clinic-1',
    staff_id: staffId,
    menu_id: menuId,
    patient_id: null,
    patient_name: patientName,
    patient_phone: phone ?? null,
    referral_name: null,
    start_at: start.toISOString(),
    end_at: end.toISOString(),
    status,
    memo: memo ?? null,
    created_at: NOW,
    updated_at: NOW,
  }
}

export const DEMO_RESERVATIONS: Reservation[] = [
  makeReservation('res-1', TODAY, 9, 30, 50, 'staff-1', 'menu-2', '山本 太郎', 'confirmed', '090-1111-2222'),
  makeReservation('res-2', TODAY, 10, 30, 30, 'staff-1', 'menu-1', '小林 由美', 'confirmed', '090-3333-4444'),
  makeReservation('res-3', TODAY, 11, 0, 90, 'staff-1', 'menu-8', '新患 一郎', 'confirmed', '080-5555-6666', '腰痛で初めての来院'),
  makeReservation('res-4', TODAY, 9, 30, 30, 'staff-2', 'menu-5', '松本 花子', 'confirmed', '090-7777-8888'),
  makeReservation('res-5', TODAY, 10, 30, 50, 'staff-2', 'menu-2', '渡辺 健', 'visited'),
  makeReservation('res-6', TODAY, 13, 0, 20, 'staff-2', 'menu-4', '伊藤 恵', 'confirmed'),
  makeReservation('res-7', TODAY, 9, 30, 50, 'staff-3', 'menu-6', '中村 勇', 'confirmed', '080-1234-5678'),
  makeReservation('res-8', TODAY, 11, 0, 20, 'staff-3', 'menu-4', '加藤 幸', 'cancelled'),
  makeReservation('res-9', TODAY, 14, 0, 30, 'staff-3', 'menu-1', '橋本 隆', 'confirmed'),
  // 翌日
  makeReservation('res-10', format(addDays(new Date(), 1), 'yyyy-MM-dd'), 10, 0, 50, 'staff-1', 'menu-2', '木村 優', 'confirmed'),
  makeReservation('res-11', format(addDays(new Date(), 1), 'yyyy-MM-dd'), 14, 0, 30, 'staff-2', 'menu-5', '林 浩二', 'confirmed'),
  // 昨日
  makeReservation('res-12', format(addDays(new Date(), -1), 'yyyy-MM-dd'), 10, 0, 50, 'staff-1', 'menu-2', '野村 敏', 'visited'),
  makeReservation('res-13', format(addDays(new Date(), -1), 'yyyy-MM-dd'), 15, 0, 90, 'staff-2', 'menu-8', '池田 初子', 'no_show'),
]

export const DEMO_SHIFTS: Shift[] = []

// 今週のシフト生成
const weekDays = [0, 1, 2, 3, 4, 5, 6]
weekDays.forEach((offset) => {
  const date = format(addDays(new Date(WEEK_START), offset), 'yyyy-MM-dd')
  const dayOfWeek = (new Date(date).getDay() + 6) % 7 // 0=月...6=日
  if (dayOfWeek < 5) { // 月〜金
    DEMO_SHIFTS.push({
      id: `shift-1-${date}`,
      staff_id: 'staff-1',
      clinic_id: 'clinic-1',
      work_date: date,
      shift_type: 'work' as const,
      start_time: '09:30',
      end_time: '20:30',
      break_start: '13:00',
      break_end: '14:00',
      created_at: NOW,
      updated_at: NOW,
    })
    DEMO_SHIFTS.push({
      id: `shift-2-${date}`,
      staff_id: 'staff-2',
      clinic_id: 'clinic-1',
      work_date: date,
      shift_type: 'work' as const,
      start_time: '09:30',
      end_time: '20:30',
      break_start: '13:00',
      break_end: '14:00',
      created_at: NOW,
      updated_at: NOW,
    })
  }
  if (dayOfWeek < 6) { // 月〜土
    DEMO_SHIFTS.push({
      id: `shift-3-${date}`,
      staff_id: 'staff-3',
      clinic_id: 'clinic-1',
      work_date: date,
      shift_type: 'work' as const,
      start_time: '09:30',
      end_time: '20:30',
      break_start: '13:00',
      break_end: '14:00',
      created_at: NOW,
      updated_at: NOW,
    })
  }
})
